import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const containerStyle = {
    backgroundColor: '#f0f0f0',
    padding: '20px',
    borderRadius: '8px'
  };
const navBarLink = {
  borderRadius: '8px',
  borderColor: '#000000',
  borderStyle: 'outset'
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav style={{ display: 'flex', gap: '20px', padding: '10px', backgroundColor: '#333333', alignItems: 'center', }}>
          <h1 style={{ color: '#fffdfd', fontSize: '2rem' }}>Game.Review</h1>
          <Link href="/" style={navBarLink}>HOME</Link>
          <Link href="/games" style={navBarLink}>GAMES</Link>
          <Link href="/about" style={navBarLink}>ABOUT US</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
